### PR TITLE
[ImgBot] Optimize images

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
## Beep boop. Your images are optimized!

Your image file size has been reduced by **30%** 🎉

<details>
<summary>
Details
</summary>

| File | Before | After | Percent reduction |
|:--|:--|:--|:--|
| /docs/tutorial/part-two/css-modules-basic.png | 116.33kb | 58.15kb | 50.02% |
| /docs/tutorial/part-two/global-css.png | 83.16kb | 42.01kb | 49.48% |
| /docs/tutorial/part-zero/04-home-page.png | 113.90kb | 57.63kb | 49.40% |
| /docs/tutorial/part-three/about-uncentered.png | 103.39kb | 54.40kb | 47.38% |
| /docs/tutorial/part-seven/query-markdown-slugs.png | 97.54kb | 52.86kb | 45.81% |
| /docs/tutorial/part-eight/lighthouse-audit.png | 78.86kb | 44.17kb | 43.98% |
| /docs/tutorial/part-three/with-navigation2.png | 150.42kb | 85.52kb | 43.14% |
| /docs/tutorial/part-two/css-modules-console.png | 96.28kb | 55.92kb | 41.92% |
| /docs/tutorial/part-one/surge-deployment.png | 108.80kb | 64.02kb | 41.15% |
| /docs/tutorial/part-two/typography-lawton.png | 202.84kb | 119.38kb | 41.15% |
| /docs/tutorial/part-zero/02-gatsby-version.png | 84.10kb | 49.72kb | 40.87% |
| /docs/tutorial/part-three/typography-centered.png | 181.65kb | 108.14kb | 40.47% |
| /docs/tutorial/blog-netlify-cms-tutorial/netlify-install-oauth-provider.png | 104.63kb | 62.49kb | 40.28% |
| /docs/tutorial/part-two/typography-bootstrap.png | 186.60kb | 111.56kb | 40.21% |
| /docs/tutorial/part-three/typography-not-centered.png | 179.35kb | 107.54kb | 40.04% |
| /docs/tutorial/part-five/my-files-page.png | 486.55kb | 294.13kb | 39.55% |
| /docs/tutorial/part-seven/hello-world-blog-post.png | 120.01kb | 72.57kb | 39.53% |
| /docs/tutorial/part-seven/new-pages.png | 212.25kb | 128.41kb | 39.50% |
| /docs/tutorial/part-six/two-posts.png | 198.75kb | 121.20kb | 39.02% |
| /docs/tutorial/part-two/css-modules-1.png | 126.25kb | 77.29kb | 38.78% |
| /docs/tutorial/part-six/frontpage.png | 162.34kb | 99.48kb | 38.72% |
| /docs/tutorial/part-three/with-title.png | 124.87kb | 76.68kb | 38.59% |
| /docs/tutorial/part-three/with-navigation.png | 158.84kb | 97.61kb | 38.55% |
| /docs/tutorial/part-three/with-layout2.png | 142.24kb | 87.58kb | 38.43% |
| /docs/tutorial/part-three/no-layout.png | 138.22kb | 85.32kb | 38.27% |
| /docs/tutorial/part-five/data-in-console.png | 126.24kb | 79.43kb | 37.08% |
| /docs/tutorial/part-seven/markdown-relative-path.png | 54.97kb | 34.62kb | 37.01% |
| /docs/tutorial/part-three/typography-styles.png | 212.73kb | 134.22kb | 36.91% |
| /docs/tutorial/part-six/markdown-query.png | 257.30kb | 163.02kb | 36.64% |
| /docs/tutorial/part-five/filesystem-autocomplete.png | 703.04kb | 469.77kb | 33.18% |
| /docs/tutorial/part-five/allfile-query.png | 678.13kb | 455.68kb | 32.80% |
| /docs/tutorial/part-eight/lighthouse-audit-results.png | 240.55kb | 162.05kb | 32.63% |
| /docs/tutorial/part-zero/05-gatsby-help.png | 88.62kb | 60.02kb | 32.28% |
| /docs/tutorial/part-five/filesystem-explorer-options.png | 552.73kb | 375.66kb | 32.04% |
| /docs/tutorial/part-five/filesystem-query.png | 507.95kb | 346.24kb | 31.84% |
| /docs/tutorial/part-zero/01-node-npm-versions.png | 31.59kb | 21.62kb | 31.58% |
| /docs/tutorial/blog-netlify-cms-tutorial/netlify-dashboard.png | 223.47kb | 162.20kb | 27.42% |
| /docs/tutorial/part-six/markdown-autocomplete.png | 102.56kb | 76.64kb | 25.27% |
| /docs/tutorial/part-five/graphiql-filesystem.png | 531.21kb | 405.31kb | 23.70% |
| /docs/tutorial/part-one/08-duplicate-header.png | 227.54kb | 173.74kb | 23.64% |
| /docs/tutorial/part-one/06-header-component.png | 238.21kb | 182.04kb | 23.58% |
| /docs/tutorial/part-one/07-pass-data-header.png | 217.49kb | 166.70kb | 23.35% |
| /docs/tutorial/part-one/03-more-hot-reloading.png | 228.32kb | 175.23kb | 23.25% |
| /docs/tutorial/part-one/05-about-page.png | 86.74kb | 66.60kb | 23.21% |
| /docs/tutorial/part-seven/blog-post.png | 883.52kb | 678.80kb | 23.17% |
| /docs/tutorial/part-one/04-add-image.png | 410.44kb | 321.39kb | 21.70% |
| /docs/tutorial/ecommerce-tutorial/stripe-public-test-key.png | 69.31kb | 54.61kb | 21.21% |
| /docs/tutorial/part-two/glamor-example.png | 328.68kb | 260.23kb | 20.83% |
| /docs/tutorial/part-two/css-modules-final.png | 335.78kb | 266.54kb | 20.62% |
| /docs/tutorial/part-one/01-hello-world-vscode.png | 53.74kb | 43.36kb | 19.32% |
| /docs/tutorial/part-four/site-metadata-title.png | 104.46kb | 85.86kb | 17.81% |
| /docs/tutorial/part-four/site-metadata-two-titles.png | 105.17kb | 86.44kb | 17.81% |
| /docs/tutorial/part-four/pandas-eating-lots-titles.png | 103.29kb | 85.10kb | 17.61% |
| /docs/tutorial/part-four/start.png | 1,437.99kb | 1,281.30kb | 10.90% |
| | | | |
| **Total :** | **12,899.93kb** | **9,088.18kb** | **29.55%** |
</details>

---

[📝docs](https://imgbot.net/docs) | [:octocat: repo](https://github.com/dabutvin/ImgBot) | [🙋issues](https://github.com/dabutvin/ImgBot/issues) | [🏅swag](https://goo.gl/forms/1GX7wlhGEX8nkhGO2) | [🏪marketplace](https://github.com/marketplace/imgbot)

### CODE REVIEW

**Comment by MichaelDeBoey** [comment]
If you want, you can install https://imgbot.net in this repo (or in the full organization).
It will automatically send PRs for image optimization 🙂

**Comment by tesseralis** [comment]
oh geez... I didn't know there were still that many images left.

Honestly, the images don't need to be in the repo. We can just get rid of them I think.

(I was just lazy with copying the files originally)

**Comment by tesseralis** [comment]
If this is something you think would be helpful for gatsby as a whole, maybe try suggesting it in a PR to the [main gatsby repo](https://github.com/gatsbyjs/gatsby)?

**Comment by MichaelDeBoey** [comment]
@tesseralis I already put it in the main repo too (https://github.com/gatsbyjs/gatsby/pull/18964)

**Comment by MichaelDeBoey** [comment]
Closed in favor of #3

**Pull request closed without merging**
